# Generated by Django 3.2.4 on 2021-06-14 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=14)),
                ('client_email', models.EmailField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle'), ('Truck', 'Truck')], default='Car', max_length=20)),
                ('vehicle_ID', models.CharField(max_length=17)),
                ('vehicle_licence_number', models.CharField(max_length=12)),
                ('vehicle_issue_text', models.TextField()),
                ('ticket_status', models.CharField(choices=[('New', 'New'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default='New', max_length=10)),
                ('ticket_entry_date', models.DateTimeField(default=datetime.datetime(2021, 6, 14, 19, 23, 10, 599950, tzinfo=utc))),
                ('ticket_solution_date', models.DateTimeField(blank=True, null=True)),
                ('ticket_solution_text', models.TextField(blank=True, null=True)),
                ('ticket_number', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_assignee', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.question')),
            ],
        ),
    ]
