# Generated by Django 3.2.4 on 2021-06-14 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_entry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 19, 23, 47, 592317, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
