# Generated by Django 3.2.4 on 2021-06-14 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20210614_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_entry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 19, 26, 0, 328858, tzinfo=utc)),
        ),
    ]
